import forms from "@tailwindcss/forms"
import containerQueries from "@tailwindcss/container-queries"

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#bd0c3b",
        "primary-dim": "#a90032",
        "primary-fixed": "#ffaaaf",
        "primary-fixed-dim": "#ff959d",
        "primary-container": "#ffaaaf",
        "on-primary": "#fff7f6",
        "on-primary-fixed": "#570015",
        "on-primary-fixed-variant": "#8f0029",
        "on-primary-container": "#7e0023",
        "inverse-primary": "#ff506a",
        secondary: "#6e3bd8",
        "secondary-dim": "#622bcb",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#ddcdff",
        "secondary-container": "#e9ddff",
        "on-secondary": "#fdf7ff",
        "on-secondary-fixed": "#4d00b7",
        "on-secondary-fixed-variant": "#6a37d4",
        "on-secondary-container": "#6029c9",
        tertiary: "#954b00",
        "tertiary-dim": "#834100",
        "tertiary-fixed": "#ffa35d",
        "tertiary-fixed-dim": "#fa913b",
        "tertiary-container": "#ffa35d",
        "on-tertiary": "#fff7f4",
        "on-tertiary-fixed": "#371800",
        "on-tertiary-fixed-variant": "#663100",
        "on-tertiary-container": "#592a00",
        error: "#ac3149",
        "error-dim": "#770326",
        "error-container": "#f76a80",
        "on-error": "#fff7f7",
        "on-error-container": "#68001f",
        surface: "#f6fafe",
        "surface-dim": "#d0dce4",
        "surface-bright": "#f6fafe",
        "surface-variant": "#dae4eb",
        "surface-tint": "#bd0c3b",
        "surface-container": "#e8eff4",
        "surface-container-low": "#eff4f9",
        "surface-container-high": "#e1e9f0",
        "surface-container-highest": "#dae4eb",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#2a3439",
        "on-surface-variant": "#576067",
        outline: "#727c82",
        "outline-variant": "#a9b3ba",
        background: "#f6fafe",
        "on-background": "#2a3439",
        "inverse-surface": "#0a0f12",
        "inverse-on-surface": "#999da1",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [forms, containerQueries],
}
